local T={}
	T.Base ="base"
	T.Name ="The Valeyard's TARDIS"
	T.ID ="vstardis"


T.Versions = {
	randomize = true,
	allow_custom = true,
	randomize_custom = true,

	main = {
			id = "vstardis",
	},
	other = {
		{
            name = "McGann Exterior",
            id = "vstardis_mcgann",
        }
	},
}

T.Interior = {
	Model="models/valeyardstudios/int/main/walls.mdl",
	
	Portal = {
	-- Generated by portals debug tool
	pos = Vector(-2.6227098715026e-08, -237.42929077148, 48.71875),
	ang = Angle(-0, 90, 0),
	width = 60,
	height = 86,
	thickness = -5,
},


	Fallback={
		pos=Vector(0, -216, 10),
		ang=Angle(0,0,0)
	},

	ExitDistance=2800,

	Light={
		color=Color(0,150,150),
		warncolor=Color(255, 50, 50),
		pos=Vector(0, 0, 50),
		brightness=0.5
	},

	Lights= {
		{
			color = Color(0, 25, 50),
			pos = Vector(0, 100, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(100, 0, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(-100, 0, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(0, -100, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
	},
	LightOverride = {
		basebrightness = 1,
		nopowerbrightness = 0.1
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},
	IdleSound={
		{
			path="normal/hum.wav",
			volume=1
		}
	},

	Parts={
		console=false,
		door={
			model="models/valeyardstudios/int/details/doors.mdl",
			posoffset = Vector(28, 0, -48.718811035156),
			angoffset= Angle(0, 180, 0)
		},
		interiordoors = {},
		pillars = {},
		roundel1 = {},
		roundel2 = {},
		roundel3 = {},
		roundel4 = {},
		roof = {},
		main_floor = {}
	}                    
}

T.Exterior={
	Model="models/valeyardstudios/ext/ExteriorShell.mdl",
	Mass=2900,
Portal = {
	-- Generated by portals debug tool
	pos = Vector(28.013013839722, 0.026009082794189, 48.6904296875),
	ang = Angle(-0, 0, 0),
	width = 46,
	height = 85,
	thickness = 41,
	inverted = true,
},

	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 115),
		color=Color(0,155,155)
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},

Parts={
	door={
		model="models/valeyardstudios/ext/ExtDoor.mdl",
		posoffset=Vector(-28.013013839722,00,-48.6904296875),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
}

T.Interior.TextureSets = {
	["normal"] = {
		prefix = "valeyardstudios/int/main/",
				{"floor", 0, "Floor"},
				{"floor", 1, "Floor - UnLit"},

				{"pillars", 0,"Pillars"},
				{"pillars", 1, "Pillars - UnLit"},
				{"pillars", 2, "Pillars - Damaged"},

				{"roof", 0, "Roof"},
				{"roof", 1, "Roof - UnLit"},

				{"roundel1", 0, "Roundels"},
				{"roundel1", 1, "Roundels - UnLit"},
				{"roundel1", 2, "Roundels - Damaged"},

				{"roundel2", 0, "Roundels"},
				{"roundel2", 1, "Roundels - UnLit"},
				{"roundel2", 2, "Roundels - Damaged"},

				{"roundel3", 0, "Roundels"},
				{"roundel3", 1, "Roundels - UnLit"},
				{"roundel3", 2, "Roundels - Damaged"},

				{"roundel4", 0, "Roundels"},
				{"roundel4", 1, "Roundels - UnLit"},
				{"roundel4", 2, "Roundels - Damaged"},

				{"walls", 0, "Walls"},
			},
	["poweroff"] = {
		prefix = "valeyardstudios/int/main/off/",
				{"floor", 1, "Floor - UnLit"},

				{"pillars", 1, "Pillars - UnLit"},

				{"roof", 1, "Roof - UnLit"},

				{"roundel1", 1, "Roundels - UnLit"},

				{"roundel2", 1, "Roundels - UnLit"},

				{"roundel3", 1, "Roundels - UnLit"},

				{"roundel4", 1, "Roundels - UnLit"},
	},
	["warning"] = {
		prefix = "valeyardstudios/int/main/warning/",
				{"pillars", 2, "Pillars - Damaged"},

				{"roundel1", 2, "Roundels - Damaged"},

				{"roundel2", 2, "Roundels - Damaged"},

				{"roundel3", 2, "Roundels - Damaged"},

				{"roundel4", 2, "Roundels - Damaged"},
	},
}

local TEXTURE_UPDATE_DATA_IDS = {
	["power-state"] = true,
	["health-warning"] = true,
	["teleport"] = true,
	["vortex"] = true,
}

T.CustomHooks = {
	travel_textures = {
		inthooks = {
			["PowerToggled"] = true,
		},
		func = function(ext, int, data_id, data_value)

			prefix = "models/valeyardstudios"

			local power = ext:GetData("power-state")
			local warning = ext:GetData("health-warning")
			local teleport = ext:GetData("teleport")
			local vortex = ext:GetData("vortex")

			if not power then
				int:ApplyTextureSet("poweroff")
			else
				if flight or teleport or vortex then
					int:ApplyTextureSet(warning and "warning")
				else
					int:ApplyTextureSet(warning and "warning" or "normal")
				end
			end
		end,
	},
}
TARDIS:AddInterior(T)