local T={}
	T.Base ="base"
	T.IsVersionOf = "vstardis"
	T.Name ="The Valeyard's TARDIS"
	T.ID ="vstardis_mcgann"


T.Interior = {
	Model="models/valeyardstudios/int/main/walls.mdl",
	
Portal = {
	-- Generated by portals debug tool
	pos = Vector(-8.3405211626086e-08, -184, 48.71875),
	ang = Angle(-0, 90, 0),
	width = 60,
	height = 86,
	thickness = -5,
},


	Fallback={
		pos=Vector(0, -150, 15),
		ang=Angle(0,0,0)
	},

	ExitDistance=3000,

	Light={
		color=Color(0,150,150),
		warncolor=Color(255, 50, 50),
		pos=Vector(0, 0, 50),
		brightness=0.5
	},

	Lights= {
		{
			color = Color(0, 25, 50),
			pos = Vector(0, 100, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(100, 0, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(-100, 0, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(0, -100, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
	},
	LightOverride = {
		basebrightness = 1,
		nopowerbrightness = 0.1
	},

	IdleSound={
		{
			path="normal/hum.wav",
			volume=1
		}
	},

	Parts={
		console=false,
		door={
			model="models/valeyardstudios/mcgann/96IntDoors.mdl",
			posoffset = Vector(23.3172460714704, 0, -48),
			angoffset= Angle(0, 180, 0)
		},
		
		pillars = {},
		roundel1 = {},
		roundel2 = {},
		roundel3 = {},
		roundel4 = {},
		roof = {},
		main_floor = {}
	}                    
}

T.Exterior={
	Model="models/valeyardstudios/mcgann/96Shell.mdl",
	Mass=2900,
Portal = {
	-- Generated by portals debug tool
	pos = Vector(24.194982528687, 0.025998115539551, 48.099998474121),
	ang = Angle(-0, -1.0245284101984e-05, 0),
	width = 35,
	height = 85,
	thickness = 23,
	inverted = true,
},

	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 106),
		color=Color(155,155,000)
	},
	Sounds={
		Teleport={
			demat="mcgann/demat.wav",
			mat="mcgann/mat.wav",
		},
		FlightLoop="mcgann/flight.wav"
	},

Parts={
	door={
		model="models/valeyardstudios/mcgann/96Doors.mdl",
		posoffset=Vector(-24.194982528687, 0.025998115539551, -48.099998474121),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
    }
 

TARDIS:AddInterior(T)
