local T={}
	T.Base ="base"
	T.Name ="The Valeyard's TARDIS"
	T.ID ="vstardis"


T.Versions = {
	randomize = true,
	allow_custom = true,
	randomize_custom = true,

	main = {
			id = "vstardis",
	},
	other = {
		{
            name = "McGann Exterior",
            id = "vstardis_mcgann",
        }
	},
}

T.Interior = {
	Model="models/valeyardstudios/int/main/walls.mdl",

	Portal = {
	-- Generated by portals debug tool
	pos = Vector(-2.6227098715026e-08, -237.42929077148, 48.71875),
	ang = Angle(-0, 90, 0),
	width = 60,
	height = 86,
	thickness = -5,
},


	Fallback={
		pos=Vector(0, -216, 10),
		ang=Angle(0,0,0)
	},

	ExitDistance=2800,

	Light={
		color=Color(0,150,150),
		warncolor=Color(255, 25, 25),
		pos=Vector(0, 0, 50),
		brightness=0.5
	},
	Screens = {
        {
            pos = Vector(-6.25, -18, 52),
            ang = Angle(0, 0, 50),
            width = 210,
            height = 200,
            visgui_rows = 2,
            power_off_black = true
        }
    },
	Lights= {
		{
			color = Color(0,150,150),
			warncolor=Color(255, 25, 25),
			fov = 175,
			distance = 100,
			brightness = 0.05,
			pos = Vector(0, 0, 150),
			ang = Angle(90, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(0, 100, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(100, 0, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(-100, 0, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
		{
			color = Color(0, 25, 50),
			pos = Vector(0, -100, 100),
			brightness = 1,
			nopower = false,
			warncolor = Color(255, 0, 0),
		},
	},
	LightOverride = {
		basebrightness = 1,
		nopowerbrightness = 0.1
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},
	IdleSound={
		{
			path="normal/hum.wav",
			volume=1
		}
	},


	Sequences = "default_sequences",
	Parts={
		console=false,
		door={
			model="models/valeyardstudios/int/details/doors.mdl",
			posoffset = Vector(28, 0, -48.718811035156),
			angoffset= Angle(0, 180, 0)
		},
		interiordoors = {},
		pillars = {},
		console_generic_metal = {},
		console_white_metal = {},
		console_dark_metal = {},
		console_glass = {},
		console_light = {},
		roundel1 = {},
		roundel2 = {},
		roundel3 = {},
		roundel4 = {},
		roof = {},
		main_floor = {},
	},
	Controls={
		power_toggle = "power",
	}
}

T.Exterior={
	Model="models/valeyardstudios/ext/ExteriorShell.mdl",
	Mass=2900,
Portal = {
	-- Generated by portals debug tool
	pos = Vector(28.013013839722, 0.0, 48.6904296875),
	ang = Angle(-0, 0, 0),
	width = 46,
	height = 85,
	thickness = 41,
	inverted = true,
},

	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 115),
		color=Color(0,155,155)
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},

Parts={
	door={
		model="models/valeyardstudios/ext/ExtDoor.mdl",
		posoffset=Vector(-28.013013839722,00,-48.6904296875),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
}

T.Interior.TextureSets = {
	["normal"] = {
		prefix = "valeyardstudios/int/main/",
				{"main_floor", 0, "Floor"},

				{"pillars", 0,"Pillars"},

				{"roof", 0, "Roof"},

				{"roundel1", 0, "Roundels"},

				{"roundel2", 0, "Roundels"},

				{"roundel3", 0, "Roundels"},

				{"roundel4", 0, "Roundels"},

				{"walls", 0, "Walls"},

				{"console_generic_metal", 0, "C_Generic_Metal"},

				{"console_white_metal", 0, "C_White_Metal"},

				{"console_dark_metal", 0, "C_Dark_Metal"},

				{"console_glass", 0, "C_Dark_Glass"},

				{"console_light", 0, "C_Light"},

				{"power_toggle", 0, "PowerSwitch"},
			},
	["poweroff"] = {
		prefix = "valeyardstudios/int/main/off/",
				{"main_floor", 0, "Floor"},

				{"pillars", 0, "Pillars"},

				{"roof", 0, "Roof"},

				{"roundel1", 0, "Roundels"},

				{"roundel2", 0, "Roundels"},

				{"roundel3", 0, "Roundels"},

				{"roundel4", 0, "Roundels"},

				{"console_generic_metal", 0, "C_Generic_Metal"},

				{"console_white_metal", 0, "C_White_Metal"},

				{"console_dark_metal", 0, "C_Dark_Metal"},

				{"console_glass", 0, "C_Dark_Glass"},

				{"console_light", 0, "C_Light"},

				{"power_toggle", 0, "PowerSwitch"},
	},
	["warning"] = {
		prefix = "valeyardstudios/int/main/warning/",
				{"pillars", 0, "Pillars"},

				{"roundel1", 0, "Roundels"},

				{"roundel2", 0, "Roundels"},

				{"roundel3", 0, "Roundels"},

				{"roundel4", 0, "Roundels"},

				{"console_generic_metal", 0, "C_Generic_Metal"},

				{"console_white_metal", 0, "C_White_Metal"},

				{"console_dark_metal", 0, "C_Dark_Metal"},

				{"console_glass", 0, "C_Dark_Glass"},

				{"console_light", 0, "C_Light"},

				{"power_toggle", 0, "PowerSwitch"},
	},
}

local TEXTURE_UPDATE_DATA_IDS = {
	["power-state"] = true,
	["health-warning"] = true,
	["teleport"] = true,
	["vortex"] = true,
}

T.CustomHooks = {
	travel_textures = {
		exthooks = {
			["DataChanged"] = true,
		},
		func = function(ext, int, data_id, data_value)
			if not TEXTURE_UPDATE_DATA_IDS[data_id] then return end

			local power = ext:GetData("power-state")
			local warning = ext:GetData("health-warning")
			local teleport = ext:GetData("teleport")
			local vortex = ext:GetData("vortex")

			if not power then
				int:ApplyTextureSet("poweroff")
			else
				if flight or teleport or vortex then
					int:ApplyTextureSet(warning and "warning" or "normal")
				else
					int:ApplyTextureSet(warning and "warning" or "normal")
				end
			end
		end,
	},
}
TARDIS:AddInterior(T)