local E = {
    ID = "abbox_ext",
    Base = "base",
    Name = "2005 TARDIS (A/B Box)",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/ab/abshell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(32.219703674316, 0.0, 48.196189880371),
	ang = Angle(-0, 0, 0),
	width = 46.633888954121,
	height = 88.061860204726,
	thickness = 50,
	inverted = true,
},

	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 119),
		color=Color(155,150,0)
		},
Parts={
	door={
		model="models/valeyardstudios/ab/abdoorsext.mdl",
		posoffset=Vector(-32.219703674316, 0.0, -48.196189880371),
		angoffset = Angle(0,0,0)
	}
},
Teleport = {
		SequenceSpeed = 0.77,
		SequenceSpeedFast = 0.935,
		DematSequence = {
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence = {
			100,
			50,
			150,
			100,
			200,
			150,
			255
		}
      }
}

 

TARDIS:AddExterior(E)