local E = {
    ID = "alt_brach",
    Base = "base",
    Name = "Altererd Brachacki (1966)",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/alt_brach/66_shell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(26.112997055054, 0.025956524536014, 44.74),
	ang = Angle(5.0025810161003e-09, -4.268869417956e-07, 1.5610135960742e-05),
	width = 41.488207514706,
	height = 85,
	thickness = 20.174632268886,
	inverted = true,
},
	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 110),
		color=Color(155,155,155)
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},

Parts={
	vortex = {
			model = "models/valeyardstudios/vortex/vortex.mdl",
		},
	door={
		model="models/valeyardstudios/alt_brach/66_doors.mdl",
		posoffset=Vector(-26.112997055054, 0, -44.74),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequenceDelays={
			[2] = 1
			},
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
    }

 

TARDIS:AddExterior(E)