local E = {
    ID = "brackolin",
    Base = "base",
    Name = "Brackolin (1966+1996)",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/brackolin/bshell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(26.113096237183, 0.02634477801621, 46.235240936279),
	ang = Angle(-4.7005496526253e-06, 8.5377376990436e-07, 0),
	width = 44.10203338228,
	height = 80.33062559405,
	thickness = 20,
	inverted = true,
},
	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 110),
		color=Color(155,155,155)
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},

Parts={
	vortex = {
			model = "models/valeyardstudios/vortex/vortex.mdl",
		},
	door={
		model="models/valeyardstudios/brackolin/bdoors.mdl",
		posoffset=Vector(-26.113096237183, 0, -46.235240936279),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequenceDelays={
			[2] = 1
			},
		DematSequence={
			150,
			250,
			100,
			150,
			75,
			100,
			50,
			75,
			0
		},
		MatSequence={
			75,
			50,
			100,
			75,
			150,
			100,
			250,
			150,
			255
		    }
      }
    }

 

TARDIS:AddExterior(E)