local E = {
    ID = "dbox_ext",
    Base = "base",
    Name = "2010 TARDIS (D Box)",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/dboxremaster/dboxnewshell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(30, 0, 49.706214904785),
	ang = Angle(1.1672688593478e-08, -1.7075475398087e-06, -3.3350533445997e-09),
	width = 44,
	height = 87.108651693019,
	thickness = 22,
	inverted = true,
},
	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 119),
		color=Color(155,100,0)
	},
Parts={
	door={
		model="models/valeyardstudios/dboxremaster/dboxnewdoors.mdl",
		posoffset=Vector(-30, 0, -49.706214904785),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=1,
		SequenceSpeedFast=1,
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
}

 

TARDIS:AddExterior(E)