local E = {
    ID = "ebox_ext",
    Base = "base",
    Name = "2011 TARDIS (E Box)",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/eboxremaster/eboxnewshell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(30.999984741211, 0, 49.299674987793),
	ang = Angle(2.4012385324568e-07, 1.1952833119722e-05, 3.4684555885178e-06),
	width = 44,
	height = 86.060293894451,
	thickness = 22,
	inverted = true,
},
	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 119),
		color=Color(155,100,0)
		},
Parts={
	door={
		model="models/valeyardstudios/eboxremaster/eboxnewdoors.mdl",
		posoffset=Vector(-30.999984741211, 0, -49.299674987793),
		angoffset = Angle(0,0,0)
	}
},
Teleport = {
		SequenceSpeed = 0.77,
		SequenceSpeedFast = 0.935,
		DematSequence = {
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence = {
			100,
			50,
			150,
			100,
			200,
			150,
			255
		}
      }
}

 

TARDIS:AddExterior(E)