local E = {
    ID = "ebox_ext",
    Base = "base",
    Name = "2011 TARDIS (E Box)",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/tardis_e/2010_e.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(31, 0, 48.606616973877),
	ang = Angle(3.3350542327781e-09, 3.4150955343648e-06, -2.5012905080501e-09),
	width = 44,
	height = 85,
	thickness = 22,
	inverted = true,
},
	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 120),
		color=Color(155,155,0)
	},
Parts={
	door={
		model="models/valeyardstudios/tardis_e/2010_e_doors.mdl",
		posoffset=Vector(-31, 0.0123, -48.606616973877),
		angoffset = Angle(0,0,0)
	}
},
Teleport = {
		SequenceSpeed = 0.77,
		SequenceSpeedFast = 0.935,
		DematSequence = {
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence = {
			100,
			50,
			150,
			100,
			200,
			150,
			255
		}
      }
}

 

TARDIS:AddExterior(E)