local E = {
    ID = "mcgannextmk2",
    Base = "base",
    Name = "1996 TV Movie TARDIS Mk2",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/mcgannmk2/mcgannmk2shell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(27.008253097534, 4.9190812205779e-06, 46.398330688477),
	ang = Angle(5.4544802878809e-06, 1.7075475398087e-06, 1.3915511772211e-05),
	width = 39.619662541649,
	height = 81.312500268592,
	thickness = 33.2175507592,
	inverted = 1,
},


	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 110),
		color=Color(155,155,0)
	},
	Sounds={
		Teleport={
			demat="mcgann/demat.wav",
			mat="mcgann/mat.wav",
		},
		FlightLoop="mcgann/flight.wav"
	},

Parts={
	door={
		model="models/valeyardstudios/mcgannmk2/mcgannmk2doors.mdl",
		posoffset=Vector(-27.008253097534, 0, -46.2),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequenceDelays={
			[2] = 1
			},
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
    }

 

TARDIS:AddExterior(E)