local E = {
    ID = "mcgann_ext",
    Base = "base",
    Name = "1996 TV Movie TARDIS",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/mcgann/96Shell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(24, 0, 48),
	ang = Angle(-0, -1.0245284101984e-05, 0),
	width = 35,
	height = 85,
	thickness = 23,
	inverted = true,
},

	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 106),
		color=Color(155,155,0)
	},
	Sounds={
		Teleport={
			demat="mcgann/demat.wav",
			mat="mcgann/mat.wav",
		},
		FlightLoop="mcgann/flight.wav"
	},

Parts={
	door={
		model="models/valeyardstudios/mcgann/96Doors.mdl",
		posoffset=Vector(-24, 0.0125, -48),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequenceDelays={
			[2] = 1
			},
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
    }

 

TARDIS:AddExterior(E)