local T={}
	T.Base ="base"
	T.Name ="The Valeyard's TARDIS"
	T.ID ="vstardis"


T.Versions = {
	randomize = true,
	allow_custom = true,
	randomize_custom = true,

	main = {
			id = "vstardis",
	},
	other = {},
}

T.Exterior={
	Model="models/valeyardstudios/ext/ShellNoDoors.mdl",
	Mass=2900,
	Portal = {
	-- Generated by portals debug tool
	pos = Vector(27.999992370605, 1.1444091796875e-05, 46.584312438965),
	ang = Angle(8.8447695816285e-06, 0, 5.7096117416222e-06),
	width = 38.622597694572,
	height = 80,
	thickness = 22,
	inverted = true,
},

	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 110),
		color=Color(0,155,155)
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},

Parts={
	door={
		model="models/valeyardstudios/ext/ExtDoors.mdl",
		posoffset=Vector(-28,0,-46.584312438965),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequence={
			150,
			200,
			100,
			150,
			50,
			100,
			0
		},
		MatSequence={
			150,
			100,
			200,
			150,
			255
		    }
      }
    }
 

TARDIS:AddInterior(T)
